// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzCdq_Uy1Kxl0GeDq8g1wRDhPLXeP8VM',
    appId: '1:485247232682:web:e0d6ca1eec562e8ac3bed3',
    messagingSenderId: '485247232682',
    projectId: 'peepo-2a833',
    authDomain: 'peepo-2a833.firebaseapp.com',
    storageBucket: 'peepo-2a833.appspot.com',
    measurementId: 'G-SJL1YVGWD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAXrSyawepN-XzbWPms_d8JZfc-M4bwEY',
    appId: '1:485247232682:android:f749740264d25187c3bed3',
    messagingSenderId: '485247232682',
    projectId: 'peepo-2a833',
    storageBucket: 'peepo-2a833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCetKZvFdwY41p_Kn4HON8YXV9P82IxcjE',
    appId: '1:485247232682:ios:647434dccd5a9c72c3bed3',
    messagingSenderId: '485247232682',
    projectId: 'peepo-2a833',
    storageBucket: 'peepo-2a833.appspot.com',
    iosBundleId: 'com.example.peefo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCetKZvFdwY41p_Kn4HON8YXV9P82IxcjE',
    appId: '1:485247232682:ios:647434dccd5a9c72c3bed3',
    messagingSenderId: '485247232682',
    projectId: 'peepo-2a833',
    storageBucket: 'peepo-2a833.appspot.com',
    iosBundleId: 'com.example.peefo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZzCdq_Uy1Kxl0GeDq8g1wRDhPLXeP8VM',
    appId: '1:485247232682:web:60b1584279d1df16c3bed3',
    messagingSenderId: '485247232682',
    projectId: 'peepo-2a833',
    authDomain: 'peepo-2a833.firebaseapp.com',
    storageBucket: 'peepo-2a833.appspot.com',
    measurementId: 'G-DQ061PBPL3',
  );
}
